# Linux Build Configuration for Travis

language: cpp

os:
  - linux

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
sudo: required
dist: trusty

env:
  # Each line is a set of environment variables set before a build.
  # Thus each line represents a different build configuration.
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

# To avoid Go bindings related issues in LIT tests, hide Go binaries from CMake
install:
  - rm -f `which go`

script:
  - mkdir build && cd build
  - cmake -D LLVM_TARGETS_TO_BUILD="X86" -D LLVM_LIT_ARGS:STRING="-sv --no-progress-bar" -G "Unix Makefiles" -D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}  ..
  - make check-llvm-spirv -j 2
